### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [icon-project/icon-commons#15]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.1.3. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary iconcommons -w /tmp/ext iconcommons==1.1.3
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting iconcommons==1.1.3
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/054/d5967187e2399/iconcommons-1.1.3.tar.gz (8.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-d34hil14/iconcommons/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-d34hil14/iconcommons/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-d34hil14/iconcommons/pip-egg-info
         cwd: /tmp/pip-wheel-d34hil14/iconcommons/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-d34hil14/iconcommons/setup.py", line 11, in <module>
        with open(os.path.join('.', 'VERSION')) as version_file:
    FileNotFoundError: [Errno 2] No such file or directory: './VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by goldworm-icon** [comment]
Thanks for your feedback.
We will fix this bug as soon as possible.
